# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-01 04:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alarm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlarmImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='alarm-images/')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('alarm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='alarm.Alarm')),
            ],
        ),
    ]
