# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-11 02:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ftpd', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ftpuser',
            name='permissions',
            field=models.CharField(default='elradfmwM', max_length=20),
        ),
    ]
