# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-03 22:18
from __future__ import unicode_literals

import alarm.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alarm', '0004_device'),
    ]

    operations = [
        migrations.AddField(
            model_name='alarm',
            name='human_detection',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='alarmimage',
            name='image',
            field=models.ImageField(upload_to=alarm.models.image_directory_path),
        ),
    ]
