# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-12 02:19
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FTPUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_directory', models.BooleanField(default=True, help_text='e = change directory (CWD, CDUP commands)')),
                ('list_files', models.BooleanField(default=True, help_text='l = list files (LIST, NLST, STAT, MLSD, MLST, SIZE commands)')),
                ('retrieve_file', models.BooleanField(default=True, help_text='r = retrieve file from the server (RETR command)')),
                ('append_data', models.BooleanField(default=False, help_text='a = append data to an existing file (APPE command)')),
                ('delete', models.BooleanField(default=False, help_text='d = delete file or directory (DELE, RMD commands)')),
                ('rename', models.BooleanField(default=False, help_text='f = rename file or directory (RNFR, RNTO commands)')),
                ('create_dir', models.BooleanField(default=False, help_text='m = create directory (MKD command)')),
                ('store', models.BooleanField(default=False, help_text='w = store a file to the server (STOR, STOU commands)')),
                ('change_mode_perm', models.BooleanField(default=False, help_text='M = change mode/permission (SITE CHMOD command)')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
