# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-01 01:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('alarm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FTPAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alarm', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='alarm.Alarm')),
            ],
        ),
    ]
