# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-14 01:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_auto_20161014_0118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegrambot',
            name='token',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
