#!/bin/bash

CWD=$(pwd)
DJANGODIR=$CWD
DJANGO_SETTINGS_MODULE=settings.dev_settings    # which settings file should Django use
PYTHON=`which python`
VENV=${PYTHON%python}

echo "Starting $NAME as `whoami`"
echo "Using Python interpreter $PYTHON"

# Activate the virtual environment
source ${VENV}activate
export DJANGO_SETTINGS_MODULE=$DJANGO_SETTINGS_MODULE
export PYTHONPATH=$DJANGODIR:$CWD:$PYTHONPATH
