# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-26 01:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alarmprofile',
            name='name',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
